version: '3.3'

services:
  kjwikigdocker:
    image: georgesan/kjwikigdocker:latest
    restart: always
    ports:
      - "8080:8080"
    environment:
      - CATALINA_OPTS=-Xmx750m
      - KJWikiG_dataStorePath=/var/lib/kjwikigdocker
      - KJWikiG_defaultWord=WelcomeVisitors
      - KJWikiG_authenticationMode=AuthenticationModeMust
      - KJWikiG_uploadEnableURLOfOtherSite=uploadEnableURLOfOtherSite
      - KJWikiG_defaultImagePixel=320
      - KJWikiG_defaultTextWidth=-1
    volumes:
      - /var/lib/kjwikigdocker:/var/lib/kjwikigdocker

