apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claim-kjwikigdocker
  # if you want dynamic persistent volume , un-comment below
  # annotations:
  #  volume.beta.kubernetes.io/storage-class: "standard"
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
