apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "kjwikigdocker.fullname" . }}
  labels:
    app: {{ template "kjwikigdocker.fullname" . }}
    chart: {{ template "kjwikigdocker.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    {{- with .Values.metadata.labels }}
{{ toYaml . | indent 4 }}
    {{- end }}
data:
  KJWikiG_defaultWord: {{ .Values.configmap.defaultWord | quote }}
  KJWikiG_dataStorePath: {{ .Values.configmap.dataStorePath | quote }}
  JAVA_OPTS: {{ .Values.configmap.javaOpts | quote }}
