apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "kjwikigdocker.fullname" . }}
  labels:
    app: {{ template "kjwikigdocker.fullname" . }}
    chart: {{ template "kjwikigdocker.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    {{- with .Values.metadata.labels }}
{{ toYaml . | indent 4 }}
    {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "kjwikigdocker.fullname" . }}
      release: {{ .Release.Name }}

  # pod が ready 判定前に待機する秒数。tomcat上のJavaアプリとかは起動が遅いので長めに待ってあげる。
  minReadySeconds: 10

  # deployment controler が pod 起動 stalled と判定するまでの秒数。stalledになったPodは再起動される。
  progressDeadlineSeconds: 300

  # Rolling updateする場合の設定。
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%

  template:
    metadata:
      labels:
        app: {{ template "kjwikigdocker.fullname" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}-container
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: port8080
          containerPort: 8080
          protocol: TCP
        env:
        - name: KJWikiG_defaultWord
          valueFrom:
            configMapKeyRef:
              name: {{ template "kjwikigdocker.fullname" . }}
              key: defaultWord
        - name: KJWikiG_dataStorePath
          valueFrom:
            configMapKeyRef:
              name: {{ template "kjwikigdocker.fullname" . }}
              key: dataStorePath
        - name: JAVA_OPTS
          valueFrom:
            configMapKeyRef:
              name: {{ template "kjwikigdocker.fullname" . }}
              key: javaOpts
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
               fieldPath: metadata.name
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: MY_POD_SERVICE_ACCOUNT
          valueFrom:
            fieldRef:
              fieldPath: spec.serviceAccountName
        livenessProbe:
          httpGet:
            path: /kjwikigdocker/ping
            port: port8080
          initialDelaySeconds: 300
          timeoutSeconds: 5
          periodSeconds: 30
          successThreshold: 1
          failureThreshold: 10
        readinessProbe:
          httpGet:
            path: /kjwikigdocker/ping
            port: port8080
          initialDelaySeconds: 10
          timeoutSeconds: 5
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 30
        volumeMounts:
        - name: data
          mountPath: {{ .Values.persistence.mountPath }}
          subPath: {{ .Values.persistence.subPath }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
      # pod終了時、preStop処理+SIGTERM処理の時間(秒)。デフォルト30秒。この後SIGKILL処理になる。このアプリの場合はSIGTERMを受信してから保存する動作は無いので短くて良い。
      terminationGracePeriodSeconds: 5
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
      volumes:
      - name: data
      {{- if .Values.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ .Values.persistence.existingClaim | default (include "kjwikigdocker.fullname" .) }}
      {{- else }}
        emptyDir: {}
      {{- end }}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets }}
      {{- end }}
