apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "kjwikigdocker.fullname" . }}
  labels:
    app: {{ template "kjwikigdocker.fullname" . }}
    chart: {{ template "kjwikigdocker.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "kjwikigdocker.fullname" . }}
      release: {{ .Release.Name }}

  # pod が ready 判定前に待機する秒数。tomcat上のJavaアプリとかは起動が遅いので長めに待ってあげる。
  minReadySeconds: 15

  # deployment controler が pod 起動 stalled と判定するまでの秒数。stalledになったPodは再起動される。
  progressDeadlineSeconds: 480

  # Rolling updateする場合の設定。
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%

  template:
    metadata:
      labels:
        app: {{ template "kjwikigdocker.fullname" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}-container
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        # 終了時、pod内プロセスに SIGTERM を送信してからリソース削除まで待機する秒数。PVに最後のファイルを書いているかもしれないので待ってあげる。
        terminationGracePeriodSeconds: 5
        ports:
        - name: kjwikigdocker
          containerPort: 8080
          protocol: TCP
        env:
        - name: KJWikiG_defaultWord
          valueFrom:
            configMapKeyRef:
              name: {{ template "kjwikigdocker.fullname" . }}
              key: defaultWord
        - name: KJWikiG_dataStorePath
          valueFrom:
            configMapKeyRef:
              name: {{ template "kjwikigdocker.fullname" . }}
              key: dataStorePath
        livenessProbe:
          httpGet:
            path: /kjwikigdocker/ping
            port: kjwikigdocker
          initialDelaySeconds: 60
          timeoutSeconds: 5
          periodSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /kjwikigdocker/ping
            port: kjwikigdocker
          initialDelaySeconds: 60
          timeoutSeconds: 5
          periodSeconds: 10
          failureThreshold: 3
        volumeMounts:
        - name: data
          mountPath: {{ .Values.persistence.mountPath }}
          subPath: {{ .Values.persistence.subPath }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
      volumes:
      - name: data
      {{- if .Values.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ .Values.persistence.existingClaim | default (include "kjwikigdocker.fullname" .) }}
      {{- else }}
        emptyDir: {}
      {{- end }}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets }}
      {{- end }}
