apiVersion: v1
kind: Service
metadata:
  name: {{ template "kjwikigdocker.fullname" . }}
  labels:
    app: {{ template "kjwikigdocker.fullname" . }}
    chart: {{ template "kjwikigdocker.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    {{- with .Values.metadata.labels }}
{{ toYaml . | indent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: http-kjwikigdocker
    port: {{ .Values.service.port }}
    targetPort: http-port8080
    protocol: TCP
  {{- if (and (eq .Values.service.type "NodePort") (not (empty .Values.service.nodePort))) }}
    nodePort: {{ .Values.service.nodePort }}
  {{- end }}
{{- if .Values.service.externalIPs }}
  externalIPs:
{{ toYaml .Values.service.externalIPs | indent 4 }}
{{- end }}
  selector:
    app: {{ template "kjwikigdocker.fullname" . }}
    release: {{ .Release.Name }}
